name: manuscan
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  another_flushbar: ^1.12.30
  cupertino_icons: ^1.0.8
  device_info_plus: ^10.1.0
  get: ^4.7.2
  http: ^1.2.1
  image_picker: ^1.1.2
  mime: ^1.0.5 
  mobile_scanner: ^6.0.6
  mysql1: ^0.19.2
  network_info_plus: ^5.0.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Midnights on the Shore
      fonts:
        - asset: assets/fonts/Midnights on the Shore.otf
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSans-VariableFont_opsz,wght.ttf